const images = [
  {
    _id: "1",
    alt: "Couple Photography",
    image: "/Images/couple1.jpg",
    category: "Couple Photography",
    className: "Project1",
  },
  {
    _id: "2",
    alt: "Children Photography",
    image: "/Images/kid1.jpg",
    className: "Project2",
    category: "Children Photography",
  },
  {
    _id: "3",
    alt: "Family Photography",
    image: "/Images/family.jpg",
    category: "Family Photography",
    className: "Project3",
  },
  {
    _id: "4",
    alt: "Friends Photography",
    image: "/Images/friends.jpg",
    category: "Friends Photography",
    className: "Project4",
  },
  {
    _id: "5",
    alt: "Graduation Photography",
    image: "/Images/grad.jpg",
    category: "Graduation Photography",
    className: "Project5",
  },
  {
    _id: "6",
    alt: "Photographer",
    image: "/Images/photographer.jpg",
    category: "Photographer",
    className: "Project6",
  },

  {
    _id: "7",
    alt: "Wedding Photography",
    image: "/Images/wedding.jpg",
    category: "Wedding Photography",
    className: "Project7",
  },
  {
    _id: "8",
    alt: "Beauty Photography",
    image: "/Images/woman1.jpg",
    category: "Beauty Photography",
    className: "Project8",
  },
  {
    _id: "9",
    alt: "Couple Photography",
    image: "/Images/couple1.jpg",
    category: "Couple Photography",
    className: "Project9",
  },
  {
    _id: "10",
    alt: "Children Photography",
    image: "/Images/kid2.jpg",
    className: "Project10",
    category: "Children Photography",
  },
  {
    _id: "11",
    alt: "Family Photography",
    image: "/Images/family.jpg",
    category: "Family Photography",
    className: "Project11",
  },
  {
    _id: "12",
    alt: "Friends Photography",
    image: "/Images/friends.jpg",
    category: "Friends Photography",
    className: "Project12",
  },
  //   {
  //     _id: "13",
  //     alt: "Graduation Photography",
  //     image: "/Images/grad.jpg",
  //     category: "Graduation Photography",
  //     className: "Project13",
  //   },
  //   {
  //     _id: "14",
  //     alt: "Photographer",
  //     image: "/Images/photographer.jpg",
  //     category: "Photographer",
  //     className: "Project14",
  //   },
  //   {
  //     _id: "15",
  //     alt: "Wedding Photography",
  //     image: "/Images/wedding.jpg",
  //     category: "Wedding Photography",
  //     className: "Project15",
  //   },
  //   {
  //     _id: "16",
  //     alt: "Beauty Photography",
  //     image: "/Images/woman1.jpg",
  //     category: "Beauty Photography",
  //     className: "Project16",
  //   },
];

export default images;
