const weddingdata = [
  {
    _id: "1",
    alt: "Wedding Photography",
    image: "/Images/wedding4.webp",
    category: "Wedding Photography",
    className: "Wedding1",
  },
  {
    _id: "2",
    alt: "Wedding Photography",
    image: "/Images/wedding11.webp",
    className: "Wedding2",
    category: "Wedding Photography",
  },
  {
    _id: "3",
    alt: "Wedding Photography",
    image: "/Images/couple8.jpg",
    category: "Wedding Photography",
    className: "Wedding3",
  },
  {
    _id: "4",
    alt: "Wedding Photography",
    image: "/Images/wedding10.webp",
    category: "Wedding Photography",
    className: "Wedding4",
  },
  {
    _id: "5",
    alt: "Wedding Photography",
    image: "/Images/wedding25.webp",
    category: "Wedding Photography",
    className: "Wedding5",
  },
  {
    _id: "6",
    alt: "Wedding Photography",
    image: "/Images/wedding28.webp",
    category: "Wedding Photography",
    className: "Wedding6",
  },

  {
    _id: "7",
    alt: "Wedding Photography",
    image: "/Images/wedding17.webp",
    category: "Wedding Photography",
    className: "Wedding7",
  },
  {
    _id: "8",
    alt: "Wedding Photography",
    image: "/Images/wedding26.webp",
    category: "Wedding Photography",
    className: "Wedding8",
  },
  {
    _id: "9",
    alt: "Wedding Photography",
    image: "/Images/wedding34.webp",
    category: "Wedding Photography",
    className: "Wedding9",
  },
  {
    _id: "10",
    alt: "Wedding Photography",
    image: "/Images/couple8.jpg",
    className: "Wedding10",
    category: "Wedding Photography",
  },
  {
    _id: "11",
    alt: "Wedding Photography",
    image: "/Images/couple7.jpg",
    category: "Wedding Photography",
    className: "Wedding11",
  },
  {
    _id: "12",
    alt: "Wedding Photography",
    image: "/Images/couple10.jpg",
    category: "Wedding Photography",
    className: "Wedding12",
  },
  //   {
  //     _id: "13",
  //     alt: "Graduation Photography",
  //     image: "/Images/grad.jpg",
  //     category: "Graduation Photography",
  //     className: "Project13",
  //   },
  //   {
  //     _id: "14",
  //     alt: "Photographer",
  //     image: "/Images/photographer.jpg",
  //     category: "Photographer",
  //     className: "Project14",
  //   },
  //   {
  //     _id: "15",
  //     alt: "Wedding Photography",
  //     image: "/Images/wedding.jpg",
  //     category: "Wedding Photography",
  //     className: "Project15",
  //   },
  //   {
  //     _id: "16",
  //     alt: "Beauty Photography",
  //     image: "/Images/woman1.jpg",
  //     category: "Beauty Photography",
  //     className: "Project16",
  // },
];

export default weddingdata;
